In [1]:
import pystan
pystan.__version__

'2.17.1.0'

In [1]:
import pystan

schools_dat = {'J': 8,
               'y': [28,  8, -3,  7, -1,  1, 18, 12],
               'sigma': [15, 10, 16, 11,  9, 11, 10, 18]}

schools_code = """
data {
  int<lower=0> J; // number of schools
  vector[J] y; // estimated treatment effects
  vector<lower=0>[J] sigma; // s.e. of effect estimates
}

parameters {
  real mu;
  real<lower=0> tau;
  vector[J] eta;
}

transformed parameters {
  vector[J] theta = mu + tau * eta;
}

model {
  eta ~ normal(0, 1);
  y ~ normal(theta, sigma);
}
"""

sm = pystan.StanModel(model_code=schools_code)
fit = sm.sampling(data=schools_dat, iter=1000, chains=1)

INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_1b8a10ae4fc8bca012da623246b337aa NOW.


In [9]:
sm = pystan.StanModel(model_code=schools_code)

INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_1b8a10ae4fc8bca012da623246b337aa NOW.


In file included from /var/folders/y7/r162f1fd0zv1vzxkb5nktz300000gn/T/tmpirh7kdtp/stanfit4anon_model_1b8a10ae4fc8bca012da623246b337aa_729551725655581445.cpp:641:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1823:
/Users/Justin/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
/var/folders/y7/r162f1fd0zv1vzxkb5nktz300000gn/T/tmpirh7kdtp/stanfit4anon_model_1b8a10ae4fc8bca012da623246b337aa_729551725655581445.cpp:9215:30: warning: comparison of integers of diff

In [ ]:
sm.sampling(data=schools_dat, iter=1000, chains=4)

There we no compiler messages in the terminal window for compiling this. Just the error message above screaming about the syntax error.

In [4]:
sm_with_for_loops = pystan.StanModel(model_code=schools_code_with_for_loops)

INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_098ad34f53642840fd7f27473faaeca8 NOW.


And here are the compiler warnings:

```
In file included from /var/folders/y7/r162f1fd0zv1vzxkb5nktz300000gn/T/tmp7vh4b5br/stanfit4anon_model_098ad34f53642840fd7f27473faaeca8_1604521810952981958.cpp:641:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1823:
/Users/Justin/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
/var/folders/y7/r162f1fd0zv1vzxkb5nktz300000gn/T/tmp7vh4b5br/stanfit4anon_model_098ad34f53642840fd7f27473faaeca8_1604521810952981958.cpp:9215:30: warning: comparison of integers of different signs: 'Py_ssize_t' (aka 'long') and 'size_type' (aka 'unsigned long') [-Wsign-compare]
    __pyx_t_12 = ((__pyx_t_9 != __pyx_v_fitptr->param_names_oi().size()) != 0);
                   ~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/folders/y7/r162f1fd0zv1vzxkb5nktz300000gn/T/tmp7vh4b5br/stanfit4anon_model_098ad34f53642840fd7f27473faaeca8_1604521810952981958.cpp:25445:52: warning: code will never be executed [-Wunreachable-code]
        } else if (PY_VERSION_HEX >= 0x030700A0 && flag == (METH_FASTCALL | METH_KEYWORDS)) {
                                                   ^~~~
/var/folders/y7/r162f1fd0zv1vzxkb5nktz300000gn/T/tmp7vh4b5br/stanfit4anon_model_098ad34f53642840fd7f27473faaeca8_1604521810952981958.cpp:25445:38: note: silence by adding parentheses to mark code as explicitly dead
        } else if (PY_VERSION_HEX >= 0x030700A0 && flag == (METH_FASTCALL | METH_KEYWORDS)) {
                                     ^
                                     /* DISABLES CODE */ ( )
/var/folders/y7/r162f1fd0zv1vzxkb5nktz300000gn/T/tmp7vh4b5br/stanfit4anon_model_098ad34f53642840fd7f27473faaeca8_1604521810952981958.cpp:27249:26: warning: code will never be executed [-Wunreachable-code]
                module = PyImport_ImportModuleLevelObject(
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /var/folders/y7/r162f1fd0zv1vzxkb5nktz300000gn/T/tmp7vh4b5br/stanfit4anon_model_098ad34f53642840fd7f27473faaeca8_1604521810952981958.cpp:645:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/pystan/stan_fit.hpp:22:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/pystan/stan/src/stan/services/diagnose/diagnose.hpp:10:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/pystan/stan/src/stan/model/test_gradients.hpp:7:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/pystan/stan/src/stan/model/log_prob_grad.hpp:4:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/rev/mat.hpp:12:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/prim/mat.hpp:298:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/prim/arr.hpp:38:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/prim/arr/functor/integrate_ode_rk45.hpp:17:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/numeric/odeint.hpp:61:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/numeric/odeint/util/multi_array_adaption.hpp:29:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/multi_array.hpp:21:
In file included from /Users/Justin/anaconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/multi_array/base.hpp:28:
/Users/Justin/anaconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/multi_array/concept_checks.hpp:42:43: warning: unused typedef 'index_range' [-Wunused-local-typedef]
      typedef typename Array::index_range index_range;
                                          ^
/Users/Justin/anaconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/multi_array/concept_checks.hpp:43:37: warning: unused typedef 'index' [-Wunused-local-typedef]
      typedef typename Array::index index;
                                    ^
/Users/Justin/anaconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/multi_array/concept_checks.hpp:53:43: warning: unused typedef 'index_range' [-Wunused-local-typedef]
      typedef typename Array::index_range index_range;
                                          ^
/Users/Justin/anaconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/multi_array/concept_checks.hpp:54:37: warning: unused typedef 'index' [-Wunused-local-typedef]
      typedef typename Array::index index;
                                    ^
8 warnings generated.
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
[I 13:03:43.394 LabApp] Saving file at /pystan_test.ipynb
```

In [5]:
import pymc3

In [7]:
a = 5
f"""test {a}
test
test2"""

'test 5\ntest\ntest2'