#! /bin/sh
# Title: fetch_homework.sh
# Author: Griffin Chure
# Creation Date: 20160-10-06
# Purpose:
# This script iterates through all bebi103 subdirectories in a given directory
# and pulls the latest tagged release. This script also creates a grading
# branch with the name `hwXX_submission_grading`.
for dir in *bebi103/; do
  cd $dir

  # Get the name of the latest tagged release that includes 'submission'
  LATEST=$(git tag | grep '\<.*submission\>' | tail -1)
  GRADING_BRANCH=$LATEST'_grading'

  # Check that there is a latest tag
  if [[ $LATEST == "" ]]; then
    # Tell me if there is no tag
    echo $dir' has no tag; did not create branch.'
  else
    # Checkout the latest tag and make a new branch.
    git checkout tags/$LATEST -b $GRADING_BRANCH
    echo 'Pulled latest homework from '$dir
  fi

  cd ../
done
