#! /bin/sh
# Title: fetch_homework.sh
# Author: Griffin Chure
# Creation Date: 20160-10-06
# Purpose:
# This script iterates through all bebi103 subdirectories in a given directory
# and pulls the latest tagged release. This script also creates a grading
# branch with the name `hwXX_submission_grading`.
for dir in *bebi103/; do
  cd $dir

  # Get the name of the latest tagged release.
  LATEST=$(git tag | tail -1)
  GRADING_BRANCH=$LATEST'_grading'

  # Checkout the latest tag and make a new branch.
  git checkout tags/$LATEST -b $GRADING_BRANCH
  echo 'Pulled latest homework from '$dir
  cd ../
done
