#! /bin/sh
# Title: submit_grades.sh
# Author: Griffin Chure
# Creation Date: 2016-10-07
# Purpose:
# This script iterates through all bebi103 subdirectories in a given directory
# and submits graded files. This functions by merging the `hwXX_submission_grading`
# branch with master followed by deletion of the branch.
for dir in *bebi103; do
  cd $dir

  # Get the name of the grading branch
  GRADING_BRANCH=$(git tag | grep '\<hw.*\>' | tail -1)'_grading'

  # Switch to the grading branch if we are not already there.
  git checkout $GRADING_BRANCH

  # Add and commit graded files
  git add homework/*
  git commit -m 'Addition of graded file(s).'

  # Merge grading branch with master.
  git checkout master
  git pull
  git merge $GRADING_BRANCH -m  'Merge of grading branch.'
  git branch -d $GRADING_BRANCH
  git push origin master
  echo 'Grading for '$dir' pushed to repository'
  cd ../
done
